// Generated file. Do not edit.
// This file is generated by the iFlutter

// ignore_for_file: constant_identifier_names
// ignore_for_file: lines_longer_than_80_chars
class AssetsRes {
  AssetsRes._();

  static const String PROJECT_NAME = 'dishcovery_app';
  static const String PROJECT_VERSION = '1.0.0+1';
  static const String DISHCOVERY_LOGO = 'assets/images/dishcovery_logo.png';
}
